### ISSUE TITLE
Failed to install pywraps2 - Linux ubuntu 16.04

### ISSUE THREAD

**Issue by potatozrollin** [google/s2geometry#108]
Hi! I am trying to install s2geometry in my ubuntu 16.04 machine with python3.7 and I keep getting the follow error after executing the following:
````
cmake -DPYTHON_EXECUTABLE=/usr/bin/python3.7 .. && make && sudo make install
````

````
[100%] Linking CXX shared module _pywraps2.so
/usr/bin/ld: /usr/local/lib/libpython3.7m.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.7m.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
python/CMakeFiles/_pywraps2.dir/build.make:106: recipe for target 'python/_pywraps2.so' failed
make[2]: *** [python/_pywraps2.so] Error 1
CMakeFiles/Makefile2:255: recipe for target 'python/CMakeFiles/_pywraps2.dir/all' failed
make[1]: *** [python/CMakeFiles/_pywraps2.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
````

Please any help would be great. Thank you.

**Comment by jmr** [comment]
Can you try with #128?

**Comment by jmr** [comment]
#128 has been merged, you can try at HEAD.

**Comment by acm-234** [comment]
I am getting the same error as @potatozrollin on my system (Centos). I have tried using the #128 but I am still receiving the same error as described above

**Comment by jmr** [comment]
> cmake -DPYTHON_EXECUTABLE=/usr/bin/python3.7 .. && make && sudo make install

> I am getting the same error as @potatozrollin on my system (Centos).

I'm assuming you have a different command line, since PYTHON_EXECUTABLE is no longer relevant. Are you just running `cmake ..`?

What version of centos, and can you paste similar command lines and output?

> ```
> [100%] Linking CXX shared module _pywraps2.so
> /usr/bin/ld: /usr/local/lib/libpython3.7m.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
> /usr/local/lib/libpython3.7m.a: error adding symbols: Bad value
> collect2: error: ld returned 1 exit status
> python/CMakeFiles/_pywraps2.dir/build.make:106: recipe for target 'python/_pywraps2.so' failed
```

This is strange. I don't know why it's trying to use `libpython3.m.a` instead of `.so`. Can you try with `cmake -DPython3_USE_STATIC_LIBS=TRUE ..`? Maybe I should be setting that by default. Does `/usr/local/lib/libpython3.7m.so` exist?

https://cmake.org/cmake/help/git-stage/module/FindPython3.html#hints

**Comment by acm-234** [comment]
I'm using centos7.

I ran the command:
```cmake3 -DGTEST_ROOT=/path_to_googletest/googletest-release-1.8.0/googletest .. && make && make test```

Which gave the below:

```[100%] Swig compile s2.i for python
/usr/include/s2/s2region.h:45: Warning 362: operator= ignored
/usr/include/s2/s2cell_union.h:73: Warning 509: Overloaded method S2CellUnion::S2CellUnion(std::vector< uint64,std::allocator< uint64 > > const &) effectively ignored,
/usr/include/s2/s2cell_union.h:69: Warning 509: as it is shadowed by S2CellUnion::S2CellUnion(std::vector< S2CellId,std::allocator< S2CellId > >).
[100%] Built target pywraps2_swig_compilation
Scanning dependencies of target _pywraps2
[100%] Building CXX object python/CMakeFiles/_pywraps2.dir/CMakeFiles/_pywraps2.dir/s2PYTHON_wrap.cxx.o
[100%] Linking CXX shared module _pywraps2.so
[100%] Built target _pywraps2

Running tests...
 97/100 Test  #97: s2wedge_relations_test .........................   Passed    0.01 sec
        Start  98: sequence_lexicon_test
 98/100 Test  #98: sequence_lexicon_test ..........................   Passed    0.00 sec
        Start  99: value_lexicon_test
 99/100 Test  #99: value_lexicon_test .............................   Passed    0.01 sec
        Start 100: pywraps2_test
100/100 Test #100: pywraps2_test ..................................   Passed    0.09 sec

100% tests passed, 0 tests failed out of 100

Total Test time (real) = 115.88 sec
```

I then ran:

```sudo make install```

which gave:

```-- Up-to-date: /usr/local/include/gtest/internal/gtest-port.h
-- Up-to-date: /usr/local/include/gtest/internal/gtest-string.h
-- Up-to-date: /usr/local/include/gtest/internal/gtest-tuple.h
-- Up-to-date: /usr/local/include/gtest/internal/gtest-tuple.h.pump
-- Up-to-date: /usr/local/include/gtest/internal/gtest-type-util.h
-- Up-to-date: /usr/local/include/gtest/internal/gtest-type-util.h.pump
-- Installing: /usr/lib/python3.6/site-packages/_pywraps2.so
-- Set runtime path of "/usr/lib/python3.6/site-packages/_pywraps2.so" to ""
-- Installing: /usr/lib/python3.6/site-packages/pywraps2.py
```

Next I tried to import the package in python3:

```Python 3.6.8 (default, Apr  2 2020, 13:34:55) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> import pywraps2 as s2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/pywraps2.py", line 26, in <module>
    _pywraps2 = swig_import_helper()
  File "/usr/lib/python3.6/site-packages/pywraps2.py", line 22, in swig_import_helper
    _mod = imp.load_module('_pywraps2', fp, pathname, description)
  File "/usr/lib64/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib64/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libs2.so: cannot open shared object file: No such file or directory
>>> 
```

**Comment by jmr** [comment]
That's a totally different error than the OP had.

Where is `libs2.so` installed? What's the full `make install` output?

**Comment by jmr** [comment]
This is pretty old now. Closing due to staleness. Reopen if you still have a problem.
